# Generated by Django 3.1.6 on 2021-04-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betatrader', '0002_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='discount',
            field=models.FloatField(),
        ),
    ]
