# Generated by Django 3.1.6 on 2021-04-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betatrader', '0003_auto_20210428_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='expireDate',
            field=models.DateField(),
        ),
    ]
