# Generated by Django 3.1.6 on 2021-04-28 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betatrader', '0004_auto_20210428_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='affiliate',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='betatrader.partner'),
            preserve_default=False,
        ),
    ]
