# Generated by Django 3.1.6 on 2021-04-29 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betatrader', '0005_order_affiliate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='affiliate',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='betatrader.partner'),
        ),
    ]
