# Generated by Django 3.1.6 on 2021-04-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betatrader', '0006_auto_20210429_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='totalSales',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
